#include <stdio.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <string.h>
#include <cassert>
#include <iostream>
#define PORT 31415

int main()
{
    int client_fd, valread;
    struct sockaddr_in address;
    char buffer[1024] = {0};
    const char *hello = "LLorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eu massa dui. Aenean elementum lacus vitae rhoncus vulputate. Cras ac convallis ipsum. Nunc vel malesuada purus. Integer elit leo, dapibus vitae nunc vitae, gravida mattis mi. Mauris sapien tortor, elementum ut auctor eu, pharetra efficitur tellus. Cras dictum vestibulum ipsum, vitae venenatis est accumsan id. Aenean tempor mi tristique metus ultrices, eu dictum elit blandit. Vivamus egestas urna vitae tellus viverra cursus. Praesent dui elit, bibendum nec tortor in, scelerisque ultrices nulla.\
Mauris sagittis varius erat. Aliquam nec imperdiet nisi. Vestibulum sagittis dapibus erat mattis commodo. Ut non dapibus purus, eget cursus tellus. Sed ante augue, tincidunt non turpis sit amet, tempor eleifend justo. Donec vitae molestie tortor. Nunc finibus faucibus orci, in cursus dui condimentum a. Curabitur non viverra libero. Proin scelerisque felis purus, non iaculis mi mattis ac. Praesent sed consequat augue. In ultricies aliquet metus, vitae consectetur tortor dignissim id. Suspendisse sit amet varius turpis, nec sodales tellus. Vestibulum eget ornare mi.\
Sed id lacus est. Nunc sed scelerisque enim. Nullam et rhoncus justo. Cras pulvinar tortor varius feugiat mollis. Vestibulum lacus libero, volutpat laoreet maximus viverra, ornare sed mi. Donec non convallis lectus, a faucibus tortor. Maecenas lacinia ac lectus ut semper. Etiam ac finibus orci.\
Phasellus eget dolor a massa convallis tempor eget et tellus. In malesuada nisl a libero elementum ullamcorper. Praesent ipsum nulla, pretium id dapibus id, rhoncus feugiat nisi. Mauris vestibulum ultricies nunc, in tempor magna lacinia eu. Suspendisse vel viverra metus. Ut rutrum orci suscipit lacus dictum, sed porttitor magna congue. Phasellus faucibus ex ut sem fermentum, non luctus nisi laoreet. Vivamus fringilla, tellus non accumsan porttitor, risus diam aliquet nunc, id ullamcorper lorem nunc ac enim. Phasellus ligula massa, egestas sit amet dui id, porta scelerisque augue. Suspendisse potenti. Aliquam sapien metus, rutrum dapibus eleifend quis, euismod vitae ex.\
Praesent sollicitudin quam loreLLorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eu massa dui. Aenean elementum lacus vitae rhoncus vulputate. Cras ac convallis ipsum. Nunc vel malesuada purus. Integer elit leo, dapibus vitae nunc vitae, gravida mattis mi. Mauris sapien tortor, elementum ut auctor eu, pharetra efficitur tellus. Cras dictum vestibulum ipsum, vitae venenatis est accumsan id. Aenean tempor mi tristique metus ultrices, eu dictum elit blandit. Vivamus egestas urna vitae tellus viverra cursus. Praesent dui elit, bibendum nec tortor in, scelerisque ultrices nulla.\
Mauris sagittis varius erat. Aliquam nec imperdiet nisi. Vestibulum sagittis dapibus erat mattis commodo. Ut non dapibus purus, eget cursus tellus. Sed ante augue, tincidunt non turpis sit amet, tempor eleifend justo. Donec vitae molestie tortor. Nunc finibus faucibus orci, in cursus dui condimentum a. Curabitur non viverra libero. Proin scelerisque felis purus, non iaculis mi mattis ac. Praesent sed consequat augue. In ultricies aliquet metus, vitae consectetur tortor dignissim id. Suspendisse sit amet varius turpis, nec sodales tellus. Vestibulum eget ornare mi.\
Sed id lacus est. Nunc sed scelerisque enim. Nullam et rhoncus justo. Cras pulvinar tortor varius feugiat mollis. Vestibulum lacus libero, volutpat laoreet maximus viverra, ornare sed mi. Donec non convallis lectus, a faucibus tortor. Maecenas lacinia ac lectus ut semper. Etiam ac finibus orci.\
Phasellus eget dolor a massa convallis tempor eget et tellus. In malesuada nisl a libero elementum ullamcorper. Praesent ipsum nulla, pretium id dapibus id, rhoncus feugiat nisi. Mauris vestibulum ultricies nunc, in tempor magna lacinia eu. Suspendisse vel viverra metus. Ut rutrum orci suscipit lacus dictum, sed porttitor magna congue. Phasellus faucibus ex ut sem fermentum, non luctus nisi laoreet. Vivamus fringilla, tellus non accumsan porttitor, risus diam aliquet nunc, id ullamcorper lorem nunc ac enim. Phasellus ligula massa, egestas sit amet dui id, porta scelerisque augue. Suspendisse potenti. Aliquam sapien metus, rutrum dapibus eleifend quis, euismod vitae ex.\
Praesent sollicitudin quam lorLLorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eu massa dui. Aenean elementum lacus vitae rhoncus vulputate. Cras ac convallis ipsum. Nunc vel malesuada purus. Integer elit leo, dapibus vitae nunc vitae, gravida mattis mi. Mauris sapien tortor, elementum ut auctor eu, pharetra efficitur tellus. Cras dictum vestibulum ipsum, vitae venenatis est accumsan id. Aenean tempor mi tristique metus ultrices, eu dictum elit blandit. Vivamus egestas urna vitae tellus viverra cursus. Praesent dui elit, bibendum nec tortor in, scelerisque ultrices nulla.\
Mauris sagittis varius erat. Aliquam nec imperdiet nisi. Vestibulum sagittis dapibus erat mattis commodo. Ut non dapibus purus, eget cursus tellus. Sed ante augue, tincidunt non turpis sit amet, tempor eleifend justo. Donec vitae molestie tortor. Nunc finibus faucibus orci, in cursus dui condimentum a. Curabitur non viverra libero. Proin scelerisque felis purus, non iaculis mi mattis ac. Praesent sed consequat augue. In ultricies aliquet metus, vitae consectetur tortor dignissim id. Suspendisse sit amet varius turpis, nec sodales tellus. Vestibulum eget ornare mi.\
Sed id lacus est. Nunc sed scelerisque enim. Nullam et rhoncus justo. Cras pulvinar tortor varius feugiat mollis. Vestibulum lacus libero, volutpat laoreet maximus viverra, ornare sed mi. Donec non convallis lectus, a faucibus tortor. Maecenas lacinia ac lectus ut semper. Etiam ac finibus orci.\
Phasellus eget dolor a massa convallis tempor eget et tellus. In malesuada nisl a libero elementum ullamcorper. Praesent ipsum nulla, pretium id dapibus id, rhoncus feugiat nisi. Mauris vestibulum ultricies nunc, in tempor magna lacinia eu. Suspendisse vel viverra metus. Ut rutrum orci suscipit lacus dictum, sed porttitor magna congue. Phasellus faucibus ex ut sem fermentum, non luctus nisi laoreet. Vivamus fringilla, tellus non accumsan porttitor, risus diam aliquet nunc, id ullamcorper lorem nunc ac enim. Phasellus ligula massa, egestas sit amet dui id, porta scelerisque augue. Suspendisse potenti. Aliquam sapien metus, rutrum dapibus eleifend quis, euismod vitae ex.\
Praesent sollicitudin quam lorLLorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eu massa dui. Aenean elementum lacus vitae rhoncus vulputate. Cras ac convallis ipsum. Nunc vel malesuada purus. Integer elit leo, dapibus vitae nunc vitae, gravida mattis mi. Mauris sapien tortor, elementum ut auctor eu, pharetra efficitur tellus. Cras dictum vestibulum ipsum, vitae venenatis est accumsan id. Aenean tempor mi tristique metus ultrices, eu dictum elit blandit. Vivamus egestas urna vitae tellus viverra cursus. Praesent dui elit, bibendum nec tortor in, scelerisque ultrices nulla.\
Mauris sagittis varius erat. Aliquam nec imperdiet nisi. Vestibulum sagittis dapibus erat mattis commodo. Ut non dapibus purus, eget cursus tellus. Sed ante augue, tincidunt non turpis sit amet, tempor eleifend justo. Donec vitae molestie tortor. Nunc finibus faucibus orci, in cursus dui condimentum a. Curabitur non viverra libero. Proin scelerisque felis purus, non iaculis mi mattis ac. Praesent sed consequat augue. In ultricies aliquet metus, vitae consectetur tortor dignissim id. Suspendisse sit amet varius turpis, nec sodales tellus. Vestibulum eget ornare mi.\
Sed id lacus est. Nunc sed scelerisque enim. Nullam et rhoncus justo. Cras pulvinar tortor varius feugiat mollis. Vestibulum lacus libero, volutpat laoreet maximus viverra, ornare sed mi. Donec non convallis lectus, a faucibus tortor. Maecenas lacinia ac lectus ut semper. Etiam ac finibus orci.\
Phasellus eget dolor a massa convallis tempor eget et tellus. In malesuada nisl a libero elementum ullamcorper. Praesent ipsum nulla, pretium id dapibus id, rhoncus feugiat nisi. Mauris vestibulum ultricies nunc, in tempor magna lacinia eu. Suspendisse vel viverra metus. Ut rutrum orci suscipit lacus dictum, sed porttitor magna congue. Phasellus faucibus ex ut sem fermentum, non luctus nisi laoreet. Vivamus fringilla, tellus non accumsan porttitor, risus diam aliquet nunc, id ullamcorper lorem nunc ac enim. Phasellus ligula massa, egestas sit amet dui id, porta scelerisque augue. Suspendisse potenti. Aliquam sapien metus, rutrum dapibus eleifend quis, euismod vitae ex.\
Praesent sollicitudin quam lorLLorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eu massa dui. Aenean elementum lacus vitae rhoncus vulputate. Cras ac convallis ipsum. Nunc vel malesuada purus. Integer elit leo, dapibus vitae nunc vitae, gravida mattis mi. Mauris sapien tortor, elementum ut auctor eu, pharetra efficitur tellus. Cras dictum vestibulum ipsum, vitae venenatis est accumsan id. Aenean tempor mi tristique metus ultrices, eu dictum elit blandit. Vivamus egestas urna vitae tellus viverra cursus. Praesent dui elit, bibendum nec tortor in, scelerisque ultrices nulla.\
Mauris sagittis varius erat. Aliquam nec imperdiet nisi. Vestibulum sagittis dapibus erat mattis commodo. Ut non dapibus purus, eget cursus tellus. Sed ante augue, tincidunt non turpis sit amet, tempor eleifend justo. Donec vitae molestie tortor. Nunc finibus faucibus orci, in cursus dui condimentum a. Curabitur non viverra libero. Proin scelerisque felis purus, non iaculis mi mattis ac. Praesent sed consequat augue. In ultricies aliquet metus, vitae consectetur tortor dignissim id. Suspendisse sit amet varius turpis, nec sodales tellus. Vestibulum eget ornare mi.\
Sed id lacus est. Nunc sed scelerisque enim. Nullam et rhoncus justo. Cras pulvinar tortor varius feugiat mollis. Vestibulum lacus libero, volutpat laoreet maximus viverra, ornare sed mi. Donec non convallis lectus, a faucibus tortor. Maecenas lacinia ac lectus ut semper. Etiam ac finibus orci.\
Phasellus eget dolor a massa convallis tempor eget et tellus. In malesuada nisl a libero elementum ullamcorper. Praesent ipsum nulla, pretium id dapibus id, rhoncus feugiat nisi. Mauris vestibulum ultricies nunc, in tempor magna lacinia eu. Suspendisse vel viverra metus. Ut rutrum orci suscipit lacus dictum, sed porttitor magna congue. Phasellus faucibus ex ut sem fermentum, non luctus nisi laoreet. Vivamus fringilla, tellus non accumsan porttitor, risus diam aliquet nunc, id ullamcorper lorem nunc ac enim. Phasellus ligula massa, egestas sit amet dui id, porta scelerisque augue. Suspendisse potenti. Aliquam sapien metus, rutrum dapibus eleifend quis, euismod vitae ex.\
Praesent sollicitudin quam lorm, quis faucibus nunc porta et. Phasellus cursus facilisis malesuada. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut id ex at felis interdum pharetra. Etiam velit mi, scelerisque eu mi a, venenatis semper ligula. Donec eget nunc sem. Donec pharetra urna at ipsum consectetur placerat. Quisque vel tincidunt nibh. Aliquam maximus, ex non feugiat faucibus, ex metus mattis arcu, eget pulvinar est lectus sed dui. Etiam iaculis leo id lorem eleifend pretium. Quisque consequat lectus neque. Mauris velit nunc, posuere eu lacus id, commodo rhoncus lacus. Mauris facilisis vel justo posuere bibendum.";
    
    assert((client_fd = socket(AF_INET, SOCK_STREAM, 0)) != -1);
   
    address.sin_family = AF_INET;
    address.sin_port = htons(PORT);

    assert(inet_pton(AF_INET, "127.0.0.1", &address.sin_addr) != -1);
    assert(!connect(client_fd, (sockaddr *)&address, sizeof(address)));
    
    send(client_fd, hello, strlen(hello), 0);
    std::cout << "message sent" << std::endl;
    // valread = read( sock , buffer, 1024);
    // printf("%s\n",buffer );
    return 0;
}